server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.75.135
  rabbitmq:
    virtual-host: /cr
    host: 192.168.75.135
    username: cr
    password: 123qwe123
    publisher-confirm-type: correlated
    publisher-returns: true
thread:
  pool:
    coreSize: 100
    maxSize: 500
    keepalive: 60
    blockQueueSize: 1000

feign:
  sentinel:
    enabled: true

auth:
  jwt:
    pubKeyPath: e:\\project\\rsa\\rsa.pub
    cookieName: GMALL-TOKEN

