server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.135:3306/guli_cart
    username: root
    password: Chen@123
  redis:
    host: 192.168.75.135
  task:
    execution:
      thread-name-prefix: cart-task-
      pool:
        core-size: 100
        max-size: 500
        queue-capacity: 1000
        keep-alive: 60s
        allow-core-thread-timeout: false #核心线程数是否可伸缩
      shutdown:
        await-termination: true
        await-termination-period: 60
  rabbitmq:
    virtual-host: /cr
    host: 192.168.75.135
    username: cr
    password: 123qwe123
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        prefetch: 1
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: e:\\project\\rsa\\rsa.pub
    cookieName: GMALL-TOKEN
    userKey: userKey
    expire: 8640000
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
