server:
  port: 18082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.135:3306/guli_oms?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Chen@123
  redis:
    host: 192.168.75.135
    port: 6379
  rabbitmq:
    virtual-host: /cr
    host: 192.168.75.135
    username: cr
    password: 123qwe123
    listener:
      simple:
        concurrency: 3
        prefetch: 1
        acknowledge-mode: manual
    publisher-returns: true
    publisher-confirm-type: correlated
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
