server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  zipkin:
    locator:
      discovery:
        enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  redis:
    host: 192.168.75.135
    port: 6379
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug

thread:
  pool:
    coreSize: 100
    maximumPoolSize: 500
    keepAliveTime: 60
    blockingQueueSize: 2000

