server:
  port: 18081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  zipkin:
    locator:
      discovery:
        enabled: false
    base-url: http://localhost:9411
    sender:
      type: web
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.135:3306/guli_pms?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Chen@123
  redis:
    host: 192.168.75.135
    port: 6379
  jackson:
    date-format: yyyy-MM-dd
  rabbitmq:
    host: 192.168.75.135
    virtual-host: /cr
    username: cr
    password: 123qwe123
    port: 5672
    #配置生产者确认，确保消息到达交换机 :simple-同步阻塞确认,性能低，correlated-异步确认，none
    publisher-confirm-type: correlated
    #配置消息是否到达队列的确认机制
    publisher-returns: true
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/pms/**/*.xml
  type-aliases-package: com.atguigu.gmall.pms.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto