server:
  port: 18084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.75.135
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.75.135:3306/guli_ums?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Chen@123
  rabbitmq:
    host: 192.168.75.135
    virtual-host: /cr
    username: cr
    password: 123qwe123
    port: 5672
    #配置生产者确认，确保消息到达交换机 :simple-同步阻塞确认,性能低，correlated-异步确认，none
    publisher-confirm-type: correlated
    #配置消息是否到达队列的确认机制
    publisher-returns: true
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:/mapper/ums/**/*.xml
  type-aliases-package: com.atguigu.gmall.ums.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
